### ISSUE TITLE
Search session filters not working

### ISSUE THREAD

**Issue by LVerhulst4321** [LVerhulst4321/PlanZ#103]
I've found that the Search Sessions page is not filtering the sessions as requested. For example, when the Track of Literature is selected, all sessions are still being displayed.
I've done a little bit of review, but don't see any reason why this is happening.
I was wondering if any else is seeing this issue?

**Comment by bcholmes** [comment]
There's a comment at the end of the query in the EOB block in retrieve.php. I can't help but wonder it that's causing everything appended afterwards to be treated like a comment.

**Comment by bcholmes** [comment]
I just did a quick experiment where I removed the comment and it looks like that's your culprit.

**Comment by lostcarpark** [comment]
Good catch!
I suspect the line break after the comment may not being getting picked up, so appended conditions are getting treated as part of the comment.
Personally I find mixing SQL comments inside PHP strings messy at best.
I would suggest declaring a variable, before the SQL block:
```
$sessionEditCodes = '1,2,6';   // 1=brainstorm,2=vetted,3=editme
```
Then you can just reference it in the SQL:
```
    WHERE
        SEH.sessioneditcode IN ($sessionEditCodes)
```
Also note the numbers in the comment don't match the numbers in the expression.
