### ISSUE TITLE
Participant social media links

### ISSUE THREAD

**Issue by LVerhulst4321** [LVerhulst4321/PlanZ#110]
I would like to add a participant's social media links to the db and allow the participant to fill out these fields.

I am considering adding the fields to the ParticipantDetails table. Or I could do a separate table.

Fields I am thinking to add:
facebook_link
instagram_link
linkedin_link
tiktok_link
twitch_link
twitter_link
website_link
youtube_link
other_link

I am also considering where to allow the participant to enter the values. I could modify the profile page and add a section for the links. (I like this best.) Or I could add a separate page. Or I could modify the personal details page, but it's currently labeled as "Optional Demographic Details", which would need to be changed.

Thoughts?

**Comment by bcholmes** [comment]
I thought James was taking a crack at that, but he hasn't made much comment about it recently. So maybe he's paused.

Some folks will have multiples of some of those links (e.g. they want to promote their own Twitter and the Twitter account of their podcast). So I'd probably advocate for something that doesn't limit how many of these things folks can have.

**Comment by bcholmes** [comment]
I trust you recall [this discussion area](https://github.com/LVerhulst4321/PlanZ/discussions/23)

**Comment by LVerhulst4321** [comment]
Doh! I forgot about the discussion area. I'll close this issue and go re-read that and think about it.

**Comment by lostcarpark** [comment]
I have done some work on this, but it got parked by other things. I'll dig it out and see where it's got to.
I was taking the approach of adding a participant_link table, with a link type field, rather than lots of individual link fields.

**Comment by bcholmes** [comment]
I wasn't trying to push you to close the issue: just trying to remind you of some past discussion.

**Comment by lostcarpark** [comment]
Happy to keep it open, and discuss my work in progress on it.

**Comment by LVerhulst4321** [comment]
No worries! :-) Let's discuss on the discussion item. I'm looking at adding stuff for Capricon.
