### ISSUE TITLE
Add Expand All to participant Session Search Results page

### ISSUE THREAD

**Issue by LVerhulst4321** [LVerhulst4321/PlanZ#112]
I've been asked to add an Expand All button to the participant's Session Search Results page.
File: PartSearchSessionsSubmit.php

As far as I can tell, the page is currently using the bootstrap collapse function per session. There is reference to a multi target collapse option in the bootstrap docs. https://getbootstrap.com/docs/4.5/components/collapse/

Before I spend more time on this, I would like to know if this looks like a good route to go down and try. Thoughts?

Thanks!

**Comment by lostcarpark** [comment]
I'd agree that looks like the way to go. It should be relatively straightforward to add a link or button to Expand All (and a corresponding Collapse All).

The tricky part will be listing all the collapsed sections in the `aria-controls` property. I think it's shouldn't be too hard to fashion a XSL query for this, though if you can't get that to work, you could try preparing the value in the PHP and passing in.
