### ISSUE TITLE
Issue with Show Bio button at bottom of Assign Participant screen

### ISSUE THREAD

**Issue by LVerhulst4321** [LVerhulst4321/PlanZ#33]
I am having an issue with the "Show Bio" button at the bottom of the Assign Participant screen.
File: StaffAssignParticipants.php

I pull up a session. I then pull up a person who has a bio and nothing happens when I click the button. No error in the console, no error I can see. I checked on my old version of Zambia that we used for Capricon and it works fine.
![image](https://user-images.githubusercontent.com/25570607/159834748-eb2efda6-a78c-42f4-a1b9-dd310889a218.png)

Can others replicate the issue? Any ideas?

**Comment by bcholmes** [comment]
Does the network traffic give you a clue? Could there be some Javascript that hasn't correctly bound to the event?

**Comment by lostcarpark** [comment]
Just checked on mine. I hadn't actually got around to setting up any sessions under PlanZ, so I've now restored a live database and run all the updates.

The show bio seems to work fine for me. It shows the bio in a speech bubble.

It does look a little weird - Everything seems to be stacked vertically. I think it would be nice thinks like buttons were positioned on the same line, but the functionality seems to be all there for me.

**Comment by LVerhulst4321** [comment]
James, regarding the "stacked vertically" issue - if you include PR #32 that I just merged into main, that should fix that issue. But please check the Show Bio button again after including my PR changes.

BC, how do I look at the network traffic? I am still learning how to debug websites.

**Comment by bcholmes** [comment]
Each of the main browsers comes with "developer tools" (they used to be hidden and you'd have to go through magic steps to make them not-hidden). For example, [here's the instructions](https://firefox-source-docs.mozilla.org/devtools-user/index.html) for Firefox developer tools. The console is usually in the same place so maybe you have it already?

The developer tools usually open up in a separate panel that has several tabs. One of those tabs is usually a Network tab. The network tab is really useful if you want to see what's being sent to and received from the server. In Firefox, you have to open the Network tab at least once to turn on Network recording. If you think the "show bio" button is meant to fetch something from the server (I'm not sure how it's meant to work; I haven't touched it), you can check to see if something was sent to the server and if the server request looks the way you expect it to look.

**Comment by lostcarpark** [comment]
Ah yes, I've rebased main and that's fixed the formatting.

The bio button is still happily working for me on my local test site, so it doesn't look like anything in the latest change that's causing it for you.

I've had a look on the Chicon test site, and I'm getting the same issue as you there, so it would appear the problem is on that site, and not confined to your browser. I can see in the Response tab under Network that the bio is getting sent. The response for the Chicon site and my local site looks identical.

**Comment by LVerhulst4321** [comment]
BC, thank you for the notes about the Network tab in the developer tools. I've not used that tab yet. I'm using Chrome, by the way, if that's of interest. I'll look at this tool more after my work day.

James, thank you for doing some investigation! I should have noted in the original message that it was on the Chicon dev site that I was getting the issue. I'll look at it more after my work day and will probably send a note to the environment admin to see if they have any advice.

**Comment by bcholmes** [comment]
It looks funky on my test environment, too. I'll take a gander at it tonight when I have more time. It's a weird call, what with being XML-based rather than REST/JSON (the way the universe intended things).

**Comment by LVerhulst4321** [comment]
Yeah, that page is a really ugly coded page. I kind of hate it.

**Comment by bcholmes** [comment]
@lostcarpark Big agree.

**Comment by LVerhulst4321** [comment]
Soooooo many things that need improvement!

**Comment by bcholmes** [comment]
FYI... I think I see the problem. The XML response that comes back starts with whitespace (why? I dunno). As a result, the portion of jQuery that parses XML is barfing. And then everything gives up.

You *could* hunt down why the XML has some leading whitespace, but I suspect that the fastest path to the happy place is to just JSON-ify it.

**Comment by LVerhulst4321** [comment]
Thank you for finding the issue BC. I have no idea why that extra whitespace is being included. :-(
I would fix it if I knew how. Or if I knew how to change things to JSON-ify it. It looks like that "fetch_participant" call is used in a few different places in the code and so they would all have to be updated, right?

**Comment by bcholmes** [comment]
You *could* just JSONify them as you find them. Like, create a new fetch_participant call that works with JSON and update this instance, but update others as they pop up. If you want, I could take a stab at it.

I don't know why the extra white space is showing up; it might have something to do with your webserver (or could be anything, really). Are you running behind Apache? Is it a Windoze box (it could be a carriage-return-line-feed thing)?

**Comment by LVerhulst4321** [comment]
If you have time, please take a stab at it. I don't know how to write JSON or to JSONify things. It's on my "to learn" list. I know (mostly) php, html and SQL and even that knowledge is rather bare.
