### ISSUE TITLE
PR #36 Causes bug on server

### ISSUE THREAD

**Issue by LVerhulst4321** [LVerhulst4321/PlanZ#37]
The code for PR #36 causes a different bug now on the Chicon 8 dev server. No issues on my test server.
![image](https://user-images.githubusercontent.com/25570607/160471612-c8da1926-13a7-43b4-91a0-989f27a3c880.png)

The code in the fetch_participant.php is using mysqli_fetch_object and this message is saying, I think, that it should be mysqli_fetch_array. 

Thoughts?

**Comment by LVerhulst4321** [comment]
Ah ha! Figured it out! The variable $result was being used twice - as the result object from the query and as the result array being returned.

**Comment by bcholmes** [comment]
Sorry about that.

It's weird that it didn't manifest on my server. Different MySQL or PHP version, maybe?

**Comment by LVerhulst4321** [comment]
Yeah, it was very weird. It didn't manifest on my test server either. Only on the Chicon dev server. My test server is running PHP Version 7.4.28 and the Chicon dev server is running PHP Version 8.1.3. Could be related to that, maybe. But I'm happy that I was able to figure it out! I used that Network tab in the Inspect tools - that showed me the error and was very useful!

**Comment by lostcarpark** [comment]
I didn't get a change to test on my environment, but that makes a lot of sense.
I suspect the while statement is holding a reference to the initial $result, so doesn't care that it's overwritten in PHP7.4.
PHP8 is a lot stricter than previous versions, and a number of sloppy coding practices that were tolerated in before will outright fail.
