### ISSUE TITLE
Wiscon branding on Brainstorm "Submit a session".

### ISSUE THREAD

**Issue by lostcarpark** [LVerhulst4321/PlanZ#82]
There are several places that Wiscon branding is present on the Brainstorming page.

Things that are working at present:
- Correct site logo from theme displayed in header.
- "Submissions are open for programming for <con name>."

Things that need improving:
- Favicon currently has Wiscon logo. Would be nice if also could take the site theme one. Presumably the same mechanism used for the header logo should work.
- Navigation bar has Wiscon links hard coded. I think this is already available to app, so hopefully this can be added to navigation bar.
- Footer bar has "site maintained by SF3..." hard coded. It would be good if this text could either be defined in db_name or CustomText.
- Sidebar "What are we looking for? WisCon...". Ideally this should be coming from CustomText.
- Page `<title>` currently hard coded to "WisCon Panel Idea Submission/Brainstorm".

I'm hosting several convention PlanZ sites (although only one is using Brainstorming so far). It would make my life easier if I can deploy one Brainstorming "build", and have customisation through settings/tables.

**Comment by bcholmes** [comment]
If this can wait until the weekend, I don't mind tackling it.

**Comment by lostcarpark** [comment]
There's no particular urgency, but I've created PG #83, which fixes the FavIcon the same way the header image does.

**Comment by LVerhulst4321** [comment]
Thanks for finding this. I haven't tested the Brainstorm stuff much.

**Comment by bcholmes** [comment]
I think that this should be closed, now. Do you agree?

**Comment by LVerhulst4321** [comment]
Agreed. Capricon is now using the Brainstorm function and we haven't seen any Wiscon branding.

**Comment by lostcarpark** [comment]
Sounds good to me.
