### ISSUE TITLE
Add Configuration Page

### ISSUE THREAD

**Issue by lostcarpark** [LVerhulst4321/PlanZ#85]
I've been working on a page for editing the site configuration.

On load it carries out the following steps:
- Verifies the user has admin permission.
- Reads the `db_name_sample.php` file.
- Parses the file, separating any lines before the first `define`.
- Displays a HTML table listing the setting name, the default value (from sample file), the current live value (from the current active constants), and any comments following.

When Save pressed to save changes, it also carries out the following steps:
- Load the current live `db_name.php` to get the initial lines before the first `define`.
- Copy the current live settings to db_name_backup_N.php where N increments by 1.
- Save the prefix lines from the form submitted values with names and comments from sample file to a temporary file.
- Rename temporary file to db_name.php.
- Catch and display any errors when saving.

I'm not quite ready to open a pull request, but I've uploaded the current version to a branch: https://github.com/lostcarpark/PlanZ/tree/ConfigSettings

I'd appreciate if anyone could try it out and provide feedback.

Overall, I'm very happy with how well it works, and it gives admin users the ability to edit configuration without needing to edit the file directly, without needing access to the webserver back end.

Some considerations:
- Currently anyone with the Administrator role can access the page. It may be preferable to create a new privilege so access can be taken away, as not all sites may want to use it.
- Any custom `define`s not in the sample file will not be retained. This is deliberate, as I feel keeping the sample file in step with the active one is crucial, but if sites are using custom settings, it could cause problems.
- The form does not use an XML template. Adding one would add significant development effort for little gain.
- There is not much validation of the submitted form values at present, as it's assumed it will only be used by trusted administrators. It may be worth adding some additional checks.
- At present the type of the setting is inferred from its value. We may want to add support for additional types, or add more explicit typing, perhaps using the comments.
- I prepare messages when saving the file. However, due to the page redirect, these never get displayed. It would be nice to find a way to display the message after the page reload.

**Comment by LVerhulst4321** [comment]
I like the direction this is going. My initial review of the PR is that it looks ok.

**Comment by lostcarpark** [comment]
Any thoughts on what you'd like to see to get this merged?
This change has the potential to break things badly, so it's important to put sufficient safeguards in place. However, I'm using it on two production sites, and so far it has worked well.
One thing I like is that it uses db_name_sample as the definition of what constants should be defined, so when migrating changes that define new constants, I can load the configuration editor and just press "save", and it will add any new constants.

**Comment by LVerhulst4321** [comment]
Sorry. Just haven't had a chance to test it out. I'll do that very soon.

**Comment by lostcarpark** [comment]
No worries. I think it has the potential to screw up badly if it's not implemented correctly, so it's important to check it thoroughly.
And if you think of any additional safeguards, please flag them.

**Comment by LVerhulst4321** [comment]
I found a "bug" with this. Everything worked fine in my local test env. However, when I loaded it into my prod Capricon env, it wouldn't work because the config folder permissions didn't allow write access. The issue is that everything looked like it worked. No error displayed or anything. Can you add something to check the folder permissions when this option is run?

**Comment by lostcarpark** [comment]
Oh yes, the web app needs to have write permission on the config file, and the folder containing it. I need to do some testing with permissions disabled on the dev env.

The ideal would be to test when loading the form, and disable the submit button if permissions are not correct. I'll have to look at what PHP commands are available for testing permissions.

**Comment by lostcarpark** [comment]
I've opened PF #105 to check for write permission when loading the configuration editor.

**Comment by lostcarpark** [comment]
Just realised that I created the config editor with an indent level of 2 rather than 4 as in the rest of the project.
Sorry about that. My editor detects the indent level when editing existing files, but when creating new files uses my own default of 2.
I will submit a PR to correct, but I want to make the only change the indent level, and keep separate from other PRs.

**Comment by LVerhulst4321** [comment]
Everything has been working for me.

**Comment by lostcarpark** [comment]
I think this can be closed.
